### ISSUE TITLE
форма ввода проекта:название

### ISSUE THREAD

**Issue by PavelUtlik** [vliplianina/team-9b-volunteers#1]
1)не указали ограничение по количеству символов(3-100)
2)формат ввода : string
3)не указана связь между полями "название" и "сокращенное название" (например при вводе названия может автоматически формироваться сокращенное название и далее можно его выбрать из выпадающего списка)

**Comment by vliplianina** [comment]
Заголовок не отражает суть дефекта. Пример:
Форма ввода проекта:  уточнить требования к полю "Название"
Прошу учесть при последующем выполнении задания.

По п.1-2 требования обновлены.
п.3: логической взаимозависимости между полями "Название" и "Сокращённое название" не требуется. Поля заполняются вручную.
