### ISSUE TITLE
Форма ввода персоны: уточнить требования к полю "Отчество"

### ISSUE THREAD

**Issue by Mariia5656** [vliplianina/team-9b-volunteers#11]
Необходимо уточнить, какие типы значений являются валидными для заполнения (кириллица, латиница, цифры и т.д.), а также уточнить максимальное и минимальное допустимое количество вводимых символов. Необходимо уточнить, является ли поле обязательным для заполнения, доступно ли для редактирования.

**Comment by vliplianina** [comment]
Обязательное, доступно для редактирования, допустимы латиница [A-z], кириллица [А-я], дефис [-], апостроф ['], пробел, максимум 50 символов.
Обновлено в [требованиях](https://github.com/vliplianina/team-9b-volunteers/blob/master/TrainingTask%20-%20Requirements.md) п.7 "Форма ввода персоны (исполнителя)"
