### ISSUE TITLE
Форма ввода задачи: уточнить минимальное и максимальное количество часов для поля "Работа"

### ISSUE THREAD

**Issue by DimaLinnik** [vliplianina/team-9b-volunteers#13]
Уточнить минимальное и максимальное количество часов для поля "Работа"

**Comment by vliplianina** [comment]
Максимум 1000 часов.
Добавлено в  [ требования п. 6 "Форма ввода задачи"](https://github.com/vliplianina/team-9b-volunteers/blob/master/TrainingTask%20-%20Requirements.md)
