### ISSUE TITLE
Форма ввода задачи: уточнить маску ввода для поля "Дата начала"

### ISSUE THREAD

**Issue by DimaLinnik** [vliplianina/team-9b-volunteers#14]
Уточнить маску ввода для поля "Дата начала"

**Comment by vliplianina** [comment]
Маски нет, ручной ввод в формате дд-мм-гггг.
См. [требования п.6 "Форма ввода задачи"](https://github.com/vliplianina/team-9b-volunteers/blob/master/TrainingTask%20-%20Requirements.md)
