### ISSUE TITLE
Форма “Список задач”: дополнить требования к полю "Название"

### ISSUE THREAD

**Issue by sollent** [vliplianina/team-9b-volunteers#16]
Необходима информация том, является ли поле обязательным для заполнения, о типах значения для данного поля, граничных значениях (максимальное и минимальное кол-во символов).

**Comment by vliplianina** [comment]
На форме со списком задач нет поля "Название", доступного для заполнения. Поэтому в таблице со списком задач должны отображаться значения, которые являются допустимыми на форме ввода задачи. 
См.[требования](https://github.com/vliplianina/team-9b-volunteers/blob/master/TrainingTask%20-%20Requirements.md) п. 6. Форма ввода задачи
