### ISSUE TITLE
Форма “Список задач”: дополнить требования к полям "Дата начала" и "Дата окончания"

### ISSUE THREAD

**Issue by sollent** [vliplianina/team-9b-volunteers#17]
Необходима информация о формате даты для данных полей (ГГГГ-ММ-ДД, ДД-ММ-ГГГГ и т.д), о наличии ввода даты (ручной, выпадающий календарь), наличие условия, что дата окончания не может быть меньше даты начала. Также граничные значения дат, которы можно выбрать (например дата начала не может быть раньше текущего времени).

**Comment by vliplianina** [comment]
На форме со списком задач должны отображаться значения, которые являются допустимыми на форме ввода задачи. Формат отображения даты аналогичен формату ввода даты.
См.[требования](https://github.com/vliplianina/team-9b-volunteers/blob/master/TrainingTask%20-%20Requirements.md) п. 6. Форма ввода задачи
