### ISSUE TITLE
Форма “Список задач”: уточнить требования к полю "Статус"

### ISSUE THREAD

**Issue by sollent** [vliplianina/team-9b-volunteers#18]
Уточнить каким способом пользователь будет назначать статус на задачу (выбор чексобкса, выпадающий список и т.п).

**Comment by vliplianina** [comment]
В таблице со списком задач должны отображаться значения, которые являются допустимыми на форме ввода задачи.  На форме ввода задачи статус выбирается из выпадающего списка.
См.[требования](https://github.com/vliplianina/team-9b-volunteers/blob/master/TrainingTask%20-%20Requirements.md) п. 6. Форма ввода задачи
