### ISSUE TITLE
форма ввода названия не провалидирована

### ISSUE THREAD

**Issue by EgorGorbik** [vliplianina/team-9b-volunteers#2]
Не указано минимальное и максимальное количество символов (например: от 2 - 124).
Формат ввода данных должен быть String.

**Comment by vliplianina** [comment]
В заголовке не указано, для какой из форм ввода требуется уточнение физического ограничения поля "Название".
Для формы ввода задачи: ограничение для поля "Название": цифры [0-9], латиница [A-z], кириллица [А-я], точка [.], дефис [-], апостроф ['], слеш [/], нижнее подчеркивание [_], максимум 100 символов 
Для формы ввода проекта: ограничение для поля "Название": цифры [0-9], латиница [A-z], кириллица [А-я], точка [.], дефис [-], апостроф ['], слеш [/], нижнее подчеркивание [_],  максимум 128 символов.
Обновлено в требованиях.
