### ISSUE TITLE
поведение id записей: идентификаторы остальных записей, при удалении одной из них

### ISSUE THREAD

**Issue by EgorGorbik** [vliplianina/team-9b-volunteers#4]
При удалении записей не поясняется, как должны вести себя идентификаторы, то есть 
либо остаться так как есть по очереди создания, 
либо для каждой записи поле идентификатор переписывается со значением порядковой очереди нового списка записей.

**Comment by vliplianina** [comment]
ID записи не зависит от модификации или удаления других записей.
